@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

# Messages
### MessagesControllerGetHello
# @name MessagesControllerFindAll
GET {{baseUrl}}/messages

### MessagesControllerGetHello
# @name MessagesControllerFindOne
GET {{baseUrl}}/messages/6345

### MessagesControllerGetHello
# @name MessagesControllerFindOneAndName
GET {{baseUrl}}/messages/Pedro/6345
