@baseUrl = http://localhost:3000

###
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

# Messages
###
# @name MessagesControllerFindAll
GET {{baseUrl}}/messages
###
# @name MessagesControllerFindOne
GET {{baseUrl}}/messages/2
###
# @name MessagesControllerPost
POST {{baseUrl}}/messages
Content-Type: application/json 

{
    "text": "New message",
    "from": "Pedro",
    "to": "Gladisson"
}
###
# @name MessagesControllerPatch
PATCH {{baseUrl}}/messages/1
Content-Type: application/json 

{
    "text": "Update message",
    "read": true
}
###
# @name MessagesControllerDelete
DELETE {{baseUrl}}/messages/4

# Persons
###
# @name PersonsControllerPost
POST {{baseUrl}}/persons
Content-Type: application/json 

{
    "email": "g@gmail.com",
    "password": "GLAdisson@",
    "name": "Gladisson"
}
###
# @name PersonsControllerFindAll
GET {{baseUrl}}/persons
###
# @name PersonsControllerFindOne
GET {{baseUrl}}/persons/8
###
# @name PersonsControllerDelete
DELETE {{baseUrl}}/persons/2
###
# @name PersonsControllerPatch
PATCH {{baseUrl}}/persons/6
Content-Type: application/json 

{
    "password": "Mario@123"
}