@baseUrl = http://localhost:3000

###
# @name AppControllerGetHello
GET {{baseUrl}}/home/hello

# Messages
###
# @name MessagesControllerFindAll
GET {{baseUrl}}/messages
###
# @name MessagesControllerFindOne
GET {{baseUrl}}/messages/2
###
# @name MessagesControllerFindOneAndName
GET {{baseUrl}}/messages/1/Pedro
###
# @name MessagesControllerQueryParameters
GET {{baseUrl}}/messages/?limit=100&offset=50&user=pedro
###
# @name MessagesControllerPost
POST {{baseUrl}}/messages
Content-Type: application/json 

{
    "text": "New message",
    "from": "Pedro",
    "for": "Gladisson",
    "read": false,
    "date": "2026-02-04T13:30:29.696Z"
}
###
# @name MessagesControllerPatch
PATCH {{baseUrl}}/messages/2
Content-Type: application/json 

{
    "text": "Update message",
    "from": "Pedro",
    "for": "Luiz",
    "read": false,
    "date": "2026-02-04T13:30:29.696Z"
}
###
# @name MessagesControllerDelete
DELETE {{baseUrl}}/messages/3
